name: ci/cd
on:
  push:
    branches:
      - main
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Setup ANTLR
        run: pip3 install antlr4-tools
      - name: Clean install dependencies
        run: pnpm install
      - name: Audit signatures
        run: pnpm audit signatures
      - name: Generate ANTLR files
        run: pnpm run antlr
      - name: Verify
        run: pnpm run verify
      - name: Build
        run: pnpm run build
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*" # recommended by semantic-release
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Setup ANTLR
        run: pip3 install antlr4-tools
      - name: Install dependencies
        run: pnpm install
      - name: Generate ANTLR files
        run: pnpm run antlr
      - name: Build
        run: pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
